# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d57db817131598255edf8f4543f79fda2d9f1034189f67b4464993d70d3ba31866c5b9b6ea3f15f10b548a2ae7c6225857e5022339ee38def2860ff76f49a981

test:
  secret_key_base: a75eadf0cf8cc4dc7727f9dd524a8226fece9c7892b02b324a93140d54641c5b88eb245028463451d46f6237a9d25cc6c977dfada71af7ccedd4df1e29802036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
